#!/usr/bin/env bash
#
# Build .env from Key Vault + the storage account.
#
# Copy-pasting these by hand has gone wrong twice: a vault link is a *pointer*, and
# pasting the link (or a key into an endpoint slot) produces failures that look like
# network errors. This fetches the values directly so there is nothing to transcribe.
#
#   ./scripts/load_env_from_vault.sh
#
# Prints names and status only, never values.
#
set -euo pipefail

VAULT="${VAULT:-Group7-8}"
STORAGE_ACCOUNT="${STORAGE_ACCOUNT:-mobtrainingstorage}"
STORAGE_RG="${STORAGE_RG:-MOB}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

command -v az >/dev/null || { echo "az CLI not found" >&2; exit 1; }
az account show >/dev/null 2>&1 || { echo "Not logged in. Run: az login" >&2; exit 1; }

SECRETS=(
  AISearchAPIKEY
  AISearchEnpoint
  Group7-7OpenAIAPIKey
  Group7-8OpenAIEndPoint
  Group7-8text-embedding-3-large-APIKEY
  Group7-8text-embedding-3-large-Endpoint
)

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "$ENV_FILE.bak"
  echo "Backed up existing .env -> .env.bak"
fi

echo "Reading from vault '$VAULT'..."
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by scripts/load_env_from_vault.sh — do not commit."
  echo
} > "$TMP"

failed=0
for name in "${SECRETS[@]}"; do
  if value="$(az keyvault secret show --vault-name "$VAULT" --name "$name" --query value -o tsv 2>/dev/null)"; then
    # An endpoint must be a URL, and a key must not be. Catching the swap here is the
    # whole point — it is invisible once it reaches the SDK, which just reports a
    # connection error.
    # Case-insensitive: the secrets use Endpoint, EndPoint and the misspelled Enpoint.
    lower_name="$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]')"
    case "$lower_name" in
      *endpoint|*enpoint)
        if [[ "$value" != https://* ]]; then
          echo "  ! $name does not look like a URL — check the vault entry"
          failed=1
        elif [[ "$value" == *vault.azure.net* ]]; then
          echo "  ! $name contains a vault link, not an endpoint — check the vault entry"
          failed=1
        else
          echo "  ok $name"
        fi
        ;;
      *)
        if [[ "$value" == https://* ]]; then
          echo "  ! $name looks like a URL, expected a key — check the vault entry"
          failed=1
        else
          echo "  ok $name"
        fi
        ;;
    esac
    printf '%s=%s\n' "$name" "$value" >> "$TMP"
  else
    echo "  ! $name could not be read from vault '$VAULT'"
    failed=1
  fi
done

echo
echo "Reading storage connection string for '$STORAGE_ACCOUNT'..."
if conn="$(az storage account show-connection-string \
             --name "$STORAGE_ACCOUNT" --resource-group "$STORAGE_RG" \
             --query connectionString -o tsv 2>/dev/null)"; then
  printf '\nAZURE_STORAGE_CONNECTION_STRING=%s\n' "$conn" >> "$TMP"
  echo "  ok AZURE_STORAGE_CONNECTION_STRING"
else
  echo "  ! could not read the connection string"
  failed=1
fi

cat >> "$TMP" <<'SETTINGS'

# Optional overrides — uncomment only if `quizgen doctor` says a default is wrong.
# AZURE_OPENAI_CHAT_DEPLOYMENT=gpt-5
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT=text-embedding-3-large
# DOCUMENT_CONTAINERS=company-docs:ALL,software-engineering-docs:SWE
QUIZGEN_PROVIDER=mock
SETTINGS

mv "$TMP" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT

echo
echo "Wrote $ENV_FILE"
[[ $failed -eq 0 ]] || echo "Some entries looked wrong — see the ! lines above."
echo "Next:  PYTHONPATH=src .venv/bin/python -m quizgen.cli doctor"
